/**
 * AUTO-GENERATED by scripts/generate-search-index.js
 * Do not hand-edit the array below — re-run the script instead.
 * Generated: 2026-08-15T10:53:49.594Z
 *
 * To add field-level search entries (specific form fields inside a page),
 * add them to src/config/searchIndex.manual.ts instead, with type: 'field'.
 */
import type { SearchIndexItem } from './searchIndex.types';

export const generatedSearchIndex: SearchIndexItem[] = [
  {
    "label": "Account Settings",
    "path": "/account-settings",
    "module": "Account Settings",
    "type": "module",
    "id": "module:/account-settings:Account Settings"
  },
  {
    "label": "ACCOUNT SETTINGS",
    "path": "/account-settings",
    "module": "Account Settings",
    "type": "submodule",
    "id": "submodule:/account-settings:ACCOUNT SETTINGS"
  },
  {
    "label": "Business Details",
    "path": "/account-settings/BusinessPage",
    "module": "Account Settings",
    "type": "submodule",
    "id": "submodule:/account-settings/BusinessPage:Business Details"
  },
  {
    "label": "Personal Details",
    "path": "/account-settings/PersonalPage",
    "module": "Account Settings",
    "type": "submodule",
    "id": "submodule:/account-settings/PersonalPage:Personal Details"
  },
  {
    "label": "Role Management",
    "path": "/account-settings/RoleManagementPage",
    "module": "Account Settings",
    "type": "submodule",
    "id": "submodule:/account-settings/RoleManagementPage:Role Management"
  },
  {
    "label": "Tenant",
    "path": "/account-settings/TenantPage",
    "module": "Account Settings",
    "type": "submodule",
    "id": "submodule:/account-settings/TenantPage:Tenant"
  },
  {
    "label": "User Accounts",
    "path": "/account-settings/UserAccount",
    "module": "Account Settings",
    "type": "submodule",
    "id": "submodule:/account-settings/UserAccount:User Accounts"
  },
  {
    "label": "Master Admin",
    "path": "/master-admin",
    "module": "Master Admin",
    "type": "module",
    "id": "module:/master-admin:Master Admin"
  },
  {
    "label": "MASTER-ADMIN",
    "path": "/master-admin",
    "module": "Master Admin",
    "type": "submodule",
    "id": "submodule:/master-admin:MASTER-ADMIN"
  },
  {
    "label": "Dashboard",
    "path": "/master-admin",
    "module": "Master Admin",
    "type": "submodule",
    "id": "submodule:/master-admin:Dashboard"
  },
  {
    "label": "Discount",
    "path": "/master-admin/Discount",
    "module": "Master Admin",
    "type": "submodule",
    "id": "submodule:/master-admin/Discount:Discount"
  },
  {
    "label": "Item Master",
    "path": "/master-admin/Items",
    "module": "Master Admin",
    "type": "submodule",
    "id": "submodule:/master-admin/Items:Item Master"
  },
  {
    "label": "Category",
    "path": "/master-admin/Items/Category",
    "module": "Master Admin",
    "type": "submodule",
    "id": "submodule:/master-admin/Items/Category:Category"
  },
  {
    "label": "Inventory Type",
    "path": "/master-admin/Items/InventoryType",
    "module": "Master Admin",
    "type": "submodule",
    "id": "submodule:/master-admin/Items/InventoryType:Inventory Type"
  },
  {
    "label": "Item",
    "path": "/master-admin/Items/Item",
    "module": "Master Admin",
    "type": "submodule",
    "id": "submodule:/master-admin/Items/Item:Item"
  },
  {
    "label": "Item Group",
    "path": "/master-admin/Items/itemGroup",
    "module": "Master Admin",
    "type": "submodule",
    "id": "submodule:/master-admin/Items/itemGroup:Item Group"
  },
  {
    "label": "Measurement Type",
    "path": "/master-admin/Items/MeasurementType",
    "module": "Master Admin",
    "type": "submodule",
    "id": "submodule:/master-admin/Items/MeasurementType:Measurement Type"
  },
  {
    "label": "Order Type",
    "path": "/master-admin/Items/OrderType",
    "module": "Master Admin",
    "type": "submodule",
    "id": "submodule:/master-admin/Items/OrderType:Order Type"
  },
  {
    "label": "SFG",
    "path": "/master-admin/Items/SFG",
    "module": "Master Admin",
    "type": "submodule",
    "id": "submodule:/master-admin/Items/SFG:SFG"
  },
  {
    "label": "Sub Category",
    "path": "/master-admin/Items/Subcategory",
    "module": "Master Admin",
    "type": "submodule",
    "id": "submodule:/master-admin/Items/Subcategory:Sub Category"
  },
  {
    "label": "KOT Master",
    "path": "/master-admin/KOTMaster",
    "module": "Master Admin",
    "type": "submodule",
    "id": "submodule:/master-admin/KOTMaster:KOT Master"
  },
  {
    "label": "Add On",
    "path": "/master-admin/KOTMaster/addOn",
    "module": "Master Admin",
    "type": "submodule",
    "id": "submodule:/master-admin/KOTMaster/addOn:Add On"
  },
  {
    "label": "AddOn",
    "path": "/master-admin/KOTMaster/addOn",
    "module": "Master Admin",
    "type": "submodule",
    "id": "submodule:/master-admin/KOTMaster/addOn:AddOn"
  },
  {
    "label": "KOT Table",
    "path": "/master-admin/KOTMaster/TableMaster",
    "module": "Master Admin",
    "type": "submodule",
    "id": "submodule:/master-admin/KOTMaster/TableMaster:KOT Table"
  },
  {
    "label": "Variant",
    "path": "/master-admin/KOTMaster/variants",
    "module": "Master Admin",
    "type": "submodule",
    "id": "submodule:/master-admin/KOTMaster/variants:Variant"
  },
  {
    "label": "Locations",
    "path": "/master-admin/Locations",
    "module": "Master Admin",
    "type": "submodule",
    "id": "submodule:/master-admin/Locations:Locations"
  },
  {
    "label": "MixBox",
    "path": "/master-admin/MixBox",
    "module": "Master Admin",
    "type": "submodule",
    "id": "submodule:/master-admin/MixBox:MixBox"
  },
  {
    "label": "Online Partners",
    "path": "/master-admin/OnlinePartners",
    "module": "Master Admin",
    "type": "submodule",
    "id": "submodule:/master-admin/OnlinePartners:Online Partners"
  },
  {
    "label": "Sale Order",
    "path": "/master-admin/SaleOrder",
    "module": "Master Admin",
    "type": "submodule",
    "id": "submodule:/master-admin/SaleOrder:Sale Order"
  },
  {
    "label": "Advance Amount",
    "path": "/master-admin/SaleOrder/AdvanceAmount",
    "module": "Master Admin",
    "type": "submodule",
    "id": "submodule:/master-admin/SaleOrder/AdvanceAmount:Advance Amount"
  },
  {
    "label": "Charges",
    "path": "/master-admin/SaleOrder/Charges",
    "module": "Master Admin",
    "type": "submodule",
    "id": "submodule:/master-admin/SaleOrder/Charges:Charges"
  },
  {
    "label": "Delivery Date",
    "path": "/master-admin/SaleOrder/DeliveryDate",
    "module": "Master Admin",
    "type": "submodule",
    "id": "submodule:/master-admin/SaleOrder/DeliveryDate:Delivery Date"
  },
  {
    "label": "DeliveryDate",
    "path": "/master-admin/SaleOrder/DeliveryDate",
    "module": "Master Admin",
    "type": "submodule",
    "id": "submodule:/master-admin/SaleOrder/DeliveryDate:DeliveryDate"
  },
  {
    "label": "Delivery Type",
    "path": "/master-admin/SaleOrder/DeliveryType",
    "module": "Master Admin",
    "type": "submodule",
    "id": "submodule:/master-admin/SaleOrder/DeliveryType:Delivery Type"
  },
  {
    "label": "Events",
    "path": "/master-admin/SaleOrder/Events",
    "module": "Master Admin",
    "type": "submodule",
    "id": "submodule:/master-admin/SaleOrder/Events:Events"
  },
  {
    "label": "Payment Type",
    "path": "/master-admin/SaleOrder/PaymentType",
    "module": "Master Admin",
    "type": "submodule",
    "id": "submodule:/master-admin/SaleOrder/PaymentType:Payment Type"
  },
  {
    "label": "section",
    "path": "/master-admin/SectionMaster",
    "module": "Master Admin",
    "type": "submodule",
    "id": "submodule:/master-admin/SectionMaster:section"
  },
  {
    "label": "Section",
    "path": "/master-admin/SectionMaster",
    "module": "Master Admin",
    "type": "submodule",
    "id": "submodule:/master-admin/SectionMaster:Section"
  },
  {
    "label": "Tax",
    "path": "/master-admin/Tax",
    "module": "Master Admin",
    "type": "submodule",
    "id": "submodule:/master-admin/Tax:Tax"
  },
  {
    "label": "UOM",
    "path": "/master-admin/Uom",
    "module": "Master Admin",
    "type": "submodule",
    "id": "submodule:/master-admin/Uom:UOM"
  },
  {
    "label": "Vehicle",
    "path": "/master-admin/Vehicle",
    "module": "Master Admin",
    "type": "submodule",
    "id": "submodule:/master-admin/Vehicle:Vehicle"
  },
  {
    "label": "Warehouse",
    "path": "/master-admin/WarehouseMaster",
    "module": "Master Admin",
    "type": "submodule",
    "id": "submodule:/master-admin/WarehouseMaster:Warehouse"
  },
  {
    "label": "YEN Reports",
    "path": "/QlikReport",
    "module": "YEN Reports",
    "type": "module",
    "id": "module:/QlikReport:YEN Reports"
  },
  {
    "label": "YEN REPORTS",
    "path": "/QlikReport",
    "module": "YEN Reports",
    "type": "submodule",
    "id": "submodule:/QlikReport:YEN REPORTS"
  },
  {
    "label": "ERP Dashboard",
    "path": "/QlikReport",
    "module": "YEN Reports",
    "type": "submodule",
    "id": "submodule:/QlikReport:ERP Dashboard"
  },
  {
    "label": "Sale Order",
    "path": "/QlikReport/Pos",
    "module": "YEN Reports",
    "type": "submodule",
    "id": "submodule:/QlikReport/Pos:Sale Order"
  },
  {
    "label": "Day-End Sales",
    "path": "/QlikReport/Pos/dayend",
    "module": "YEN Reports",
    "type": "submodule",
    "id": "submodule:/QlikReport/Pos/dayend:Day-End Sales"
  },
  {
    "label": "Dispatches",
    "path": "/QlikReport/Pos/Dispatchall",
    "module": "YEN Reports",
    "type": "submodule",
    "id": "submodule:/QlikReport/Pos/Dispatchall:Dispatches"
  },
  {
    "label": "Dispatch Receive",
    "path": "/QlikReport/Pos/DispatchReceive",
    "module": "YEN Reports",
    "type": "submodule",
    "id": "submodule:/QlikReport/Pos/DispatchReceive:Dispatch Receive"
  },
  {
    "label": "Item Order",
    "path": "/QlikReport/Pos/ItemOrder",
    "module": "YEN Reports",
    "type": "submodule",
    "id": "submodule:/QlikReport/Pos/ItemOrder:Item Order"
  },
  {
    "label": "Sales by Order",
    "path": "/QlikReport/Pos/ItemOrder",
    "module": "YEN Reports",
    "type": "submodule",
    "id": "submodule:/QlikReport/Pos/ItemOrder:Sales by Order"
  },
  {
    "label": "Item Transfers",
    "path": "/QlikReport/Pos/Itemtransfer",
    "module": "YEN Reports",
    "type": "submodule",
    "id": "submodule:/QlikReport/Pos/Itemtransfer:Item Transfers"
  },
  {
    "label": "Sales by Item",
    "path": "/QlikReport/Pos/itemwise",
    "module": "YEN Reports",
    "type": "submodule",
    "id": "submodule:/QlikReport/Pos/itemwise:Sales by Item"
  },
  {
    "label": "Production Entries",
    "path": "/QlikReport/Pos/productionEntry1",
    "module": "YEN Reports",
    "type": "submodule",
    "id": "submodule:/QlikReport/Pos/productionEntry1:Production Entries"
  },
  {
    "label": "Overall Sales",
    "path": "/QlikReport/Pos/SalasReport",
    "module": "YEN Reports",
    "type": "submodule",
    "id": "submodule:/QlikReport/Pos/SalasReport:Overall Sales"
  },
  {
    "label": "Sales Summary",
    "path": "/QlikReport/Pos/SalasReport",
    "module": "YEN Reports",
    "type": "submodule",
    "id": "submodule:/QlikReport/Pos/SalasReport:Sales Summary"
  },
  {
    "label": "Sales Order",
    "path": "/QlikReport/Pos/saleOrder",
    "module": "YEN Reports",
    "type": "submodule",
    "id": "submodule:/QlikReport/Pos/saleOrder:Sales Order"
  },
  {
    "label": "Sales Orders",
    "path": "/QlikReport/Pos/saleOrder",
    "module": "YEN Reports",
    "type": "submodule",
    "id": "submodule:/QlikReport/Pos/saleOrder:Sales Orders"
  },
  {
    "label": "Stock Closing",
    "path": "/QlikReport/Pos/stockclosing",
    "module": "YEN Reports",
    "type": "submodule",
    "id": "submodule:/QlikReport/Pos/stockclosing:Stock Closing"
  },
  {
    "label": "Wastage",
    "path": "/QlikReport/Pos/wastageEntry",
    "module": "YEN Reports",
    "type": "submodule",
    "id": "submodule:/QlikReport/Pos/wastageEntry:Wastage"
  },
  {
    "label": "Wastage Received",
    "path": "/QlikReport/Pos/wastageRec",
    "module": "YEN Reports",
    "type": "submodule",
    "id": "submodule:/QlikReport/Pos/wastageRec:Wastage Received"
  },
  {
    "label": "Warehouse Returns",
    "path": "/QlikReport/Pos/wastageReceive",
    "module": "YEN Reports",
    "type": "submodule",
    "id": "submodule:/QlikReport/Pos/wastageReceive:Warehouse Returns"
  },
  {
    "label": "Purchase Order",
    "path": "/QlikReport/PurchaseOrder",
    "module": "YEN Reports",
    "type": "submodule",
    "id": "submodule:/QlikReport/PurchaseOrder:Purchase Order"
  },
  {
    "label": "AP Invoice",
    "path": "/QlikReport/PurchaseOrder/Apinvoice",
    "module": "YEN Reports",
    "type": "submodule",
    "id": "submodule:/QlikReport/PurchaseOrder/Apinvoice:AP Invoice"
  },
  {
    "label": "AP Invoice Service",
    "path": "/QlikReport/PurchaseOrder/Apinvoiceservice",
    "module": "YEN Reports",
    "type": "submodule",
    "id": "submodule:/QlikReport/PurchaseOrder/Apinvoiceservice:AP Invoice Service"
  },
  {
    "label": "Debit Note by Amount",
    "path": "/QlikReport/PurchaseOrder/DebitnoteAmountwise",
    "module": "YEN Reports",
    "type": "submodule",
    "id": "submodule:/QlikReport/PurchaseOrder/DebitnoteAmountwise:Debit Note by Amount"
  },
  {
    "label": "Debit Note by Item",
    "path": "/QlikReport/PurchaseOrder/DebitnoteItemwise",
    "module": "YEN Reports",
    "type": "submodule",
    "id": "submodule:/QlikReport/PurchaseOrder/DebitnoteItemwise:Debit Note by Item"
  },
  {
    "label": "GRN Against PO",
    "path": "/QlikReport/PurchaseOrder/grn",
    "module": "YEN Reports",
    "type": "submodule",
    "id": "submodule:/QlikReport/PurchaseOrder/grn:GRN Against PO"
  },
  {
    "label": "GRN by Item",
    "path": "/QlikReport/PurchaseOrder/Itemwisedate",
    "module": "YEN Reports",
    "type": "submodule",
    "id": "submodule:/QlikReport/PurchaseOrder/Itemwisedate:GRN by Item"
  },
  {
    "label": "Outgoing Payments",
    "path": "/QlikReport/PurchaseOrder/Outgoing",
    "module": "YEN Reports",
    "type": "submodule",
    "id": "submodule:/QlikReport/PurchaseOrder/Outgoing:Outgoing Payments"
  },
  {
    "label": "Outstanding",
    "path": "/QlikReport/PurchaseOrder/Outstanding",
    "module": "YEN Reports",
    "type": "submodule",
    "id": "submodule:/QlikReport/PurchaseOrder/Outstanding:Outstanding"
  },
  {
    "label": "Outstanding Payments",
    "path": "/QlikReport/PurchaseOrder/Outstanding",
    "module": "YEN Reports",
    "type": "submodule",
    "id": "submodule:/QlikReport/PurchaseOrder/Outstanding:Outstanding Payments"
  },
  {
    "label": "Petty Cash Expenses",
    "path": "/QlikReport/PurchaseOrder/PettycashExpense",
    "module": "YEN Reports",
    "type": "submodule",
    "id": "submodule:/QlikReport/PurchaseOrder/PettycashExpense:Petty Cash Expenses"
  },
  {
    "label": "Purchase Order",
    "path": "/QlikReport/PurchaseOrder/Purchaseorder",
    "module": "YEN Reports",
    "type": "submodule",
    "id": "submodule:/QlikReport/PurchaseOrder/Purchaseorder:Purchase Order"
  },
  {
    "label": "Purchase Orders",
    "path": "/QlikReport/PurchaseOrder/Purchaseorder",
    "module": "YEN Reports",
    "type": "submodule",
    "id": "submodule:/QlikReport/PurchaseOrder/Purchaseorder:Purchase Orders"
  },
  {
    "label": "RM Dispatch",
    "path": "/QlikReport/PurchaseOrder/rawmaterial2",
    "module": "YEN Reports",
    "type": "submodule",
    "id": "submodule:/QlikReport/PurchaseOrder/rawmaterial2:RM Dispatch"
  },
  {
    "label": "Dispatches -RM",
    "path": "/QlikReport/PurchaseOrder/rawmaterial2",
    "module": "YEN Reports",
    "type": "submodule",
    "id": "submodule:/QlikReport/PurchaseOrder/rawmaterial2:Dispatches -RM"
  },
  {
    "label": "Warehouse Stock",
    "path": "/QlikReport/PurchaseOrder/WarehouseStock",
    "module": "YEN Reports",
    "type": "submodule",
    "id": "submodule:/QlikReport/PurchaseOrder/WarehouseStock:Warehouse Stock"
  },
  {
    "label": "WhatsApp",
    "path": "/WhatsApp",
    "module": "WhatsApp",
    "type": "module",
    "id": "module:/WhatsApp:WhatsApp"
  },
  {
    "label": "WHATSAPP",
    "path": "/WhatsApp",
    "module": "WhatsApp",
    "type": "submodule",
    "id": "submodule:/WhatsApp:WHATSAPP"
  },
  {
    "label": "WhatsApp Admin",
    "path": "/WhatsApp/WhatsappAdmin",
    "module": "WhatsApp",
    "type": "submodule",
    "id": "submodule:/WhatsApp/WhatsappAdmin:WhatsApp Admin"
  },
  {
    "label": "WhatsApp Master",
    "path": "/WhatsApp/WhatsappMaster",
    "module": "WhatsApp",
    "type": "submodule",
    "id": "submodule:/WhatsApp/WhatsappMaster:WhatsApp Master"
  },
  {
    "label": "YEN Book",
    "path": "/yen-book",
    "module": "YEN Book",
    "type": "module",
    "id": "module:/yen-book:YEN Book"
  },
  {
    "label": "YEN BOOK",
    "path": "/yen-book",
    "module": "YEN Book",
    "type": "submodule",
    "id": "submodule:/yen-book:YEN BOOK"
  },
  {
    "label": "Expense Management",
    "path": "/yen-book/ExpenseManagementPage",
    "module": "YEN Book",
    "type": "submodule",
    "id": "submodule:/yen-book/ExpenseManagementPage:Expense Management"
  },
  {
    "label": "Expense Category",
    "path": "/yen-book/ExpenseManagementPage/ExpenseCategoryPage",
    "module": "YEN Book",
    "type": "submodule",
    "id": "submodule:/yen-book/ExpenseManagementPage/ExpenseCategoryPage:Expense Category"
  },
  {
    "label": "Expense Name",
    "path": "/yen-book/ExpenseManagementPage/ExpenseNamePage",
    "module": "YEN Book",
    "type": "submodule",
    "id": "submodule:/yen-book/ExpenseManagementPage/ExpenseNamePage:Expense Name"
  },
  {
    "label": "Expense Subcategory",
    "path": "/yen-book/ExpenseManagementPage/ExpenseSubcategoryPage",
    "module": "YEN Book",
    "type": "submodule",
    "id": "submodule:/yen-book/ExpenseManagementPage/ExpenseSubcategoryPage:Expense Subcategory"
  },
  {
    "label": "Outgoing Payment",
    "path": "/yen-book/OutgoingPaymentPage",
    "module": "YEN Book",
    "type": "submodule",
    "id": "submodule:/yen-book/OutgoingPaymentPage:Outgoing Payment"
  },
  {
    "label": "YEN Inventory",
    "path": "/yen-inventory",
    "module": "YEN Inventory",
    "type": "module",
    "id": "module:/yen-inventory:YEN Inventory"
  },
  {
    "label": "YEN INVENTORY",
    "path": "/yen-inventory",
    "module": "YEN Inventory",
    "type": "submodule",
    "id": "submodule:/yen-inventory:YEN INVENTORY"
  },
  {
    "label": "Outlets",
    "path": "/yen-inventory/OutletsInventoryManagement",
    "module": "YEN Inventory",
    "type": "submodule",
    "id": "submodule:/yen-inventory/OutletsInventoryManagement:Outlets"
  },
  {
    "label": "Outlets Inventory Management",
    "path": "/yen-inventory/OutletsInventoryManagement",
    "module": "YEN Inventory",
    "type": "submodule",
    "id": "submodule:/yen-inventory/OutletsInventoryManagement:Outlets Inventory Management"
  },
  {
    "label": "Approved Stock",
    "path": "/yen-inventory/OutletsInventoryManagement/ApprovedStock",
    "module": "YEN Inventory",
    "type": "submodule",
    "id": "submodule:/yen-inventory/OutletsInventoryManagement/ApprovedStock:Approved Stock"
  },
  {
    "label": "Stock Transaction / Ledger",
    "path": "/yen-inventory/OutletsInventoryManagement/ledger",
    "module": "YEN Inventory",
    "type": "submodule",
    "id": "submodule:/yen-inventory/OutletsInventoryManagement/ledger:Stock Transaction / Ledger"
  },
  {
    "label": "Physical Stock Modification",
    "path": "/yen-inventory/OutletsInventoryManagement/OutletPhysicalStockModification",
    "module": "YEN Inventory",
    "type": "submodule",
    "id": "submodule:/yen-inventory/OutletsInventoryManagement/OutletPhysicalStockModification:Physical Stock Modification"
  },
  {
    "label": "Physical Stock Variance Modification",
    "path": "/yen-inventory/OutletsInventoryManagement/OutletPhysicalStockVarianceModification",
    "module": "YEN Inventory",
    "type": "submodule",
    "id": "submodule:/yen-inventory/OutletsInventoryManagement/OutletPhysicalStockVarianceModification:Physical Stock Variance Modification"
  },
  {
    "label": "Warehouse",
    "path": "/yen-inventory/WarehouseInventoryManagement",
    "module": "YEN Inventory",
    "type": "submodule",
    "id": "submodule:/yen-inventory/WarehouseInventoryManagement:Warehouse"
  },
  {
    "label": "Warehouse Inventory Management",
    "path": "/yen-inventory/WarehouseInventoryManagement",
    "module": "YEN Inventory",
    "type": "submodule",
    "id": "submodule:/yen-inventory/WarehouseInventoryManagement:Warehouse Inventory Management"
  },
  {
    "label": "Approved Stock",
    "path": "/yen-inventory/WarehouseInventoryManagement/ApprovedStock",
    "module": "YEN Inventory",
    "type": "submodule",
    "id": "submodule:/yen-inventory/WarehouseInventoryManagement/ApprovedStock:Approved Stock"
  },
  {
    "label": "Stock Transaction / Ledger",
    "path": "/yen-inventory/WarehouseInventoryManagement/ledger",
    "module": "YEN Inventory",
    "type": "submodule",
    "id": "submodule:/yen-inventory/WarehouseInventoryManagement/ledger:Stock Transaction / Ledger"
  },
  {
    "label": "Physical Stock Modification",
    "path": "/yen-inventory/WarehouseInventoryManagement/stockModification",
    "module": "YEN Inventory",
    "type": "submodule",
    "id": "submodule:/yen-inventory/WarehouseInventoryManagement/stockModification:Physical Stock Modification"
  },
  {
    "label": "Physical Stock Variance Modification",
    "path": "/yen-inventory/WarehouseInventoryManagement/storeStockModification",
    "module": "YEN Inventory",
    "type": "submodule",
    "id": "submodule:/yen-inventory/WarehouseInventoryManagement/storeStockModification:Physical Stock Variance Modification"
  },
  {
    "label": "YEN POS",
    "path": "/yen-pos",
    "module": "YEN POS",
    "type": "module",
    "id": "module:/yen-pos:YEN POS"
  },
  {
    "label": "Cash Management",
    "path": "/yen-pos/CashManagement",
    "module": "YEN POS",
    "type": "submodule",
    "id": "submodule:/yen-pos/CashManagement:Cash Management"
  },
  {
    "label": "Opening Cash",
    "path": "/yen-pos/CashManagement/OpeningCash",
    "module": "YEN POS",
    "type": "submodule",
    "id": "submodule:/yen-pos/CashManagement/OpeningCash:Opening Cash"
  },
  {
    "label": "Petty Cash",
    "path": "/yen-pos/CashManagement/PettyCash",
    "module": "YEN POS",
    "type": "submodule",
    "id": "submodule:/yen-pos/CashManagement/PettyCash:Petty Cash"
  },
  {
    "label": "POS Devices",
    "path": "/yen-pos/POSDevicePage",
    "module": "YEN POS",
    "type": "submodule",
    "id": "submodule:/yen-pos/POSDevicePage:POS Devices"
  },
  {
    "label": "Prefix Master",
    "path": "/yen-pos/prefixMaster",
    "module": "YEN POS",
    "type": "submodule",
    "id": "submodule:/yen-pos/prefixMaster:Prefix Master"
  },
  {
    "label": "Reasons",
    "path": "/yen-pos/reasons",
    "module": "YEN POS",
    "type": "submodule",
    "id": "submodule:/yen-pos/reasons:Reasons"
  },
  {
    "label": "YEN Purchase",
    "path": "/yen-purchase",
    "module": "YEN Purchase",
    "type": "module",
    "id": "module:/yen-purchase:YEN Purchase"
  },
  {
    "label": "YEN PURCHASE",
    "path": "/yen-purchase",
    "module": "YEN Purchase",
    "type": "submodule",
    "id": "submodule:/yen-purchase:YEN PURCHASE"
  },
  {
    "label": "AP Invoice",
    "path": "/yen-purchase/ApInvoicePage",
    "module": "YEN Purchase",
    "type": "submodule",
    "id": "submodule:/yen-purchase/ApInvoicePage:AP Invoice"
  },
  {
    "label": "GRN Note",
    "path": "/yen-purchase/GrnPage",
    "module": "YEN Purchase",
    "type": "submodule",
    "id": "submodule:/yen-purchase/GrnPage:GRN Note"
  },
  {
    "label": "Purchase Item",
    "path": "/yen-purchase/PurchaseItemPage",
    "module": "YEN Purchase",
    "type": "submodule",
    "id": "submodule:/yen-purchase/PurchaseItemPage:Purchase Item"
  },
  {
    "label": "Purchase Master",
    "path": "/yen-purchase/PurchaseMaster",
    "module": "YEN Purchase",
    "type": "submodule",
    "id": "submodule:/yen-purchase/PurchaseMaster:Purchase Master"
  },
  {
    "label": "Purchase Order",
    "path": "/yen-purchase/PurchaseOrder",
    "module": "YEN Purchase",
    "type": "submodule",
    "id": "submodule:/yen-purchase/PurchaseOrder:Purchase Order"
  },
  {
    "label": "Service Order",
    "path": "/yen-purchase/ServiceOrder",
    "module": "YEN Purchase",
    "type": "submodule",
    "id": "submodule:/yen-purchase/ServiceOrder:Service Order"
  },
  {
    "label": "Vendor",
    "path": "/yen-purchase/VendorPage",
    "module": "YEN Purchase",
    "type": "submodule",
    "id": "submodule:/yen-purchase/VendorPage:Vendor"
  },
  {
    "label": "Vendors",
    "path": "/yen-purchase/VendorPage/Vendor",
    "module": "YEN Purchase",
    "type": "submodule",
    "id": "submodule:/yen-purchase/VendorPage/Vendor:Vendors"
  },
  {
    "label": "Vendor Type",
    "path": "/yen-purchase/VendorPage/VendorType",
    "module": "YEN Purchase",
    "type": "submodule",
    "id": "submodule:/yen-purchase/VendorPage/VendorType:Vendor Type"
  },
  {
    "label": "YEN Recipe",
    "path": "/yen-recipie/RecipeManagement",
    "module": "YEN Recipe",
    "type": "module",
    "id": "module:/yen-recipie/RecipeManagement:YEN Recipe"
  },
  {
    "label": "Recipe",
    "path": "/yen-recipie/RecipeManagement",
    "module": "YEN Recipe",
    "type": "submodule",
    "id": "submodule:/yen-recipie/RecipeManagement:Recipe"
  },
  {
    "label": "YEN RECIPE",
    "path": "/yen-recipie/RecipeManagement",
    "module": "YEN Recipe",
    "type": "submodule",
    "id": "submodule:/yen-recipie/RecipeManagement:YEN RECIPE"
  },
  {
    "label": "Store Kitchen Master",
    "path": "/yen-recipie/StoreKitchenMaster",
    "module": "YEN Recipe",
    "type": "submodule",
    "id": "submodule:/yen-recipie/StoreKitchenMaster:Store Kitchen Master"
  },
  {
    "label": "Settings",
    "path": "/yen-settings",
    "module": "Settings",
    "type": "module",
    "id": "module:/yen-settings:Settings"
  },
  {
    "label": "SETTINGS",
    "path": "/yen-settings",
    "module": "Settings",
    "type": "submodule",
    "id": "submodule:/yen-settings:SETTINGS"
  },
  {
    "label": "Display Settings",
    "path": "/yen-settings/DisplaySettings",
    "module": "Settings",
    "type": "submodule",
    "id": "submodule:/yen-settings/DisplaySettings:Display Settings"
  },
  {
    "label": "DISPLAY SETTINGS",
    "path": "/yen-settings/DisplaySettings",
    "module": "Settings",
    "type": "submodule",
    "id": "submodule:/yen-settings/DisplaySettings:DISPLAY SETTINGS"
  }
];
